### ISSUE TITLE
MTY_WindowSetGFX after initialisation (D3D->OpenGL) 

### ISSUE THREAD

**Issue by chadmortimer** [chrisd1100/libmatoya#36]
Changing gfx api from D3D -> openGL after window initialisation causes all rendering to sieze and produces the following error in the MTY Log

_mty_gl_ctx_present: 'wglSwapIntervalEXT' failed with error 0x0_

Attempted logic so far:

1. Pause all rendering operations
2. Sleep
3. Set Window Gfx -> MTY_GFX_NONE
4. Sleep
5. Set Window Gfx -> MTY_GFX_GL
6. Sleep
7. Resume rendering

Changing from openGL -> D3D seems to work okay

**Comment by chrisd1100** [comment]
Unfortunately I think this is impossible in Windows. The D3D and OpenGL surface systems work differently, and once D3D is initialized it will always overlay on top of the OpenGL surface. Furthermore, we will probably remove OpenGL fairly soon on Windows in favor of Vulkan (which suffers from the same issue, but thought I would mention).
