### ISSUE TITLE
event features?

### ISSUE THREAD

**Issue by haie1011** [chrisd1100/libmatoya#67]
does libmatoya plan to provide event-loop with non-blocking IO and timer??

**Comment by chrisd1100** [comment]
The current libmatoya event loop is designed to work well with native OSs that require the main thread for synchronous message processing. The exception is the browser that is entirely asynchronous with an invisible event loop under the hood. We will likely continue to treat the browser as the exception and fit it into the native model. We've thought about doing things with web workers that can make some browser stuff synchronous, but nothing concrete.
