### ISSUE TITLE
Upgrade to libssl3

### ISSUE THREAD

**Issue by pcewing** [chrisd1100/libmatoya#76]
If my understanding is correct, this library is still dependent on `libssl1.1`:
https://github.com/chrisd1100/libmatoya/blob/686e1d735d0cc0ced74f868e211270b76cd4edf5/src/unix/linux/x11/dl/libssl.h#L153-L158

Newer versions of Linux are shipping without support for `libssl1.1`. For example, this package is no longer in the default repositories for the Ubuntu 22.04 LTS. This makes getting software that depends on this library, such as Parsec, to run on said Linux distributions/versions more difficult.

As a workaround, I was able to get Parsec to run on ubuntu 22.04 by installing `libssl1.1` via:
```bash
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
```

However, this is relying on downloading/installing unofficial packages. It would be great if `libmatoya` could be updated with support for `libssl3` so that using it on newer distributions/versions is easier.

**Comment by chrisd1100** [comment]
This has been addressed here: a50a3fbd4090a0edd9fdc3c08f26460e202e5e6d. Let me know if you have any issues.
